dataware-tools/pydtk

- README.md
- pydtk/db/v2/handlers/__init__.py
- pydtk/db/v3/handlers/time_series.py
- pydtk/frontend.py
- pyproject.toml
- test/test_db.py
- test/test_io.py
- test/test_models.py
- test/test_statistics.py
- tox.ini
- Add section `[tool.poetry.extras]` to pyproject.toml
- Add markers to test scripts
- Avoid installing packages for extra features (e.g. MySQL, ROS, ...)
- Test codes with or without extra packages
> Separate extra dependencies

- .github/workflows/build_and_deploy_document.yaml
- .github/workflows/build_and_push_docker_images.yml
- .github/workflows/ci.yaml
Change the image name used in CI from `hdwlab/dataware-toolkit` to `hdwlab/pydtk`
To keep the consistency
> Fix the image name for CI

- Dockerfile
- docker-compose.yml
Install extra packages in Dockerfile
They should be installed
> Fix the issue that extra dependencies are not installed in Dockerfile

- .github/workflows/ci.yaml
- pydtk/db/v3/handlers/__init__.py
- pyproject.toml
- test/test_db.py
- Add dependency `sqlalchemy-migrate`
- Support adding columns to existing tables on DB servers other than SQLite
Bugfix
> Fix the bug that columns are not added to DB properly

- pydtk/db/v3/handlers/__init__.py
- test/test_db.py
- Add a test for migrating tables
- Fix the bug that columns in the local data-frame were not reflected in DB by V3DBHandler.
Bugfix
> Fix the bug that columns in DF were not reflected in DB

- Dockerfile
- poetry.lock
- pyproject.toml
Add `psycopg2-binary` as an extra dependency for PostgreSQL
Support for PostgreSQL
> Add extra dependencies for PostgreSQL

- pydtk/models/csv.py
- Fix AnnotationCsvModel to return valid columns and timestamps.
- For use this model for api.
> Fix AnnotationCsvModel to return valid values

- .github/workflows/ci.yaml
- Dockerfile
- poetry.lock
- pydtk/models/pointcloud/__init__.py
- pydtk/models/pointcloud/pcd.py
- pyproject.toml
- test/assets/.gitignore
- test/test_models.py
- tox.ini
Add `PCDModel` to support loading/saving `.pcd` files
To support point-cloud files
> Support for `.pcd` files

- examples/05_save_data.ipynb
- add examples for saving data
- to show simple example to saving data via pydtk
> add examples for saving data

- scripts/meti/meta_json.py
- scripts/meti/template.json
- meta情報生成スクリプトに個別ファイル・ディレクトリ単位で変換するオプションを追加
- 1ファイルだけの生成もできるようにするため
- ある程度生成が回って問題なければマージ
> Add option for meta generator

- pydtk/models/__init__.py
This patch fixes #38 .
Bug fix
> Fix the bug that function `register_model` fails with ImportError

- test/test_make_meta.py
meta-maker 用のテストを追加
テストしたいから
https://github.com/dataware-tools/pydtk/pull/33
> Add tests for meta-maker

- pydtk/bin/__init__.py
- pydtk/bin/make_meta.py
- pydtk/conf/v4.yaml
- pydtk/models/__init__.py
- pydtk/models/csv.py
- pydtk/models/json_model.py
- pydtk/models/movie.py
- pydtk/models/pointcloud/pcd.py
- pydtk/models/rosbag.py
- pydtk/utils/utils.py
- pyproject.toml
- test/test_make_meta.py
- メタ情報を生成するコマンドツール
```bash
$ make_meta --file hoge.bag --out_dir ./
```
- DB(テーブル)に登録するためにメタデータが必要だから
https://github.com/dataware-tools/pydtk/issues/32 Tools to make metadata
各モデルでの対応
以下モデルは別途実装
~- [ ] pcd~
~- [ ] movie~
> Add metadata generator

- Dockerfile
Dockerイメージ内で pydtk のコマンドが使えないバグを修正
バグ修正のため
> Fix the bug that binary files are not installed by poetry

- doc/source/CLI/01_overview.rst
- doc/source/CLI/02_db_operations.rst
- doc/source/CLI/03_model_operations.rst
- doc/source/CLI/04_io_operations.rst
- doc/source/index.rst
- pydtk/bin/cli.py
- pydtk/bin/sub_commands/__init__.py
- pydtk/bin/sub_commands/db.py
- pydtk/bin/sub_commands/io.py
- pydtk/bin/sub_commands/model.py
- pydtk/conf/v4.yaml
- pyproject.toml
`pydtk` コマンドを追加
(詳しくはドキュメントを参照のこと)
散財しているコマンドをまとめるため
> Add CLI `pydtk`

- docker/base/ubuntu-18.04-ros.Dockerfile
- docker/base/ubuntu-18.04.Dockerfile
- docker/base/ubuntu-20.04-ros.Dockerfile
- docker/base/ubuntu-20.04.Dockerfile
コンテナ内で `cv2` のインポートに失敗するバグを修正
バグ修正のため
> Fix the bug that `cv2` fails to import

- .github/workflows/on_release.yaml
- scripts/get-version.sh
Fix the bug that `get_version.sh` does not work properly
Bug fix
> Fix `get_version.sh`

- .github/workflows/build_and_deploy_document.yaml
- .github/workflows/build_and_publish_images.yml
- .github/workflows/ci.yaml
- .github/workflows/on_release.yaml
- .gitmodules
- README.md
- docker/dev/ubuntu-ros.Dockerfile
- docker/dev/ubuntu.Dockerfile
- docker/runtime/ubuntu-ros.Dockerfile
- docker/runtime/ubuntu.Dockerfile
- poetry.lock
- pydtk/db/v4/deps/__init__.py
- pydtk/db/v4/engines/mongodb.py
- pydtk/db/v4/engines/tinymongo.py
- pyproject.toml
- tox.ini
- Remove direct dependencies from `pyproject.toml`
- Add `PQL` into `pydtk.db.v4.deps`
- Update README so that users can install additional packages manually
- Change extra `mongodb` to non-extra
To address the issue that publishing PyDTK on PyPI fails with `HTTPError`
> Remove direct dependencies

- pydtk/models/movie.py
Implement `generate_contents_meta` and `generate_timestamp_meta` of GenericMovieModel
To support generating `content`, `start_timestamp`, and `end_timestamp` of a video file.
> Support generating metadata of video files

- pydtk/bin/cli.py
- test/test_cli.py
> Add feature to check PEP515 in CLI

- pydtk/bin/cli.py
Support getting version information in CLI
> Add command `version` in CLI

- pydtk/models/__init__.py
- pydtk/models/movie.py
- Add the ability to run load checks for different models.
- Add a check for `GenericMovieWithCameraTimestampCsvModel`.
- #76
> Loadable checks for different models

- docker/base/ubuntu-18.04-ros.Dockerfile
- docker/base/ubuntu-18.04.Dockerfile
- docker/base/ubuntu-20.04-ros.Dockerfile
- docker/base/ubuntu-20.04.Dockerfile
Add command `jq` to docker images
As we often use `jq` with PyDTK's CLI
> Pre-install `jq` in docker images

- pydtk/bin/cli.py
- pydtk/bin/sub_commands/status.py
- Commands for checking environment variables and DB access(only read check).
`pydtk status env`, `pydtk status access`
- Make it easier to check the above.
- https://github.com/dataware-tools/pydtk/issues/71
/kind feature
/assign @sudach
> Status checker

- poetry.lock
- pydtk/db/v4/engines/montydb.py
- pydtk/db/v4/handlers/meta.py
- pyproject.toml
- test/test_db.py
Support MontyDB in V4DBHandler
Resolves #83 
MontyDB seems to be well maintained compared to tinymongo.
> Support MontyDB

- OWNERS
- Change list of reviewers
- To assign the right person to the right job
- 関連するissueやPR番号へのリンク
- 参考にしたURLなど
> Change reviewers

- pydtk/__init__.py
- pydtk/db/exceptions.py
- pydtk/db/v4/engines/montydb.py
- pydtk/db/v4/engines/tinydb.py
- pydtk/db/v4/engines/tinymongo.py
- pydtk/db/v4/handlers/__init__.py
- pydtk/utils/utils.py
- pyproject.toml
- test/test_db.py
Resolve dataware-tools/dataware-tools#98 
To support datetime format
> Support datetime format in V4DBHandler

- pydtk/__init__.py
- pydtk/models/__init__.py
- pydtk/models/csv.py
- pydtk/models/image.py
- pydtk/models/json_model.py
- pydtk/models/movie.py
- pydtk/models/pointcloud/pcd.py
- pydtk/models/rosbag.py
- pyproject.toml
- test/test_io.py
- Fix method `is_loadable` to fix the behavior when either `contents`, `data_type`, or `data_type` is None
- Add tests for `BaseFileReader._select_model`
Bug fix
> Fix the bug that models were not selected properly

- pydtk/db/v4/engines/__init__.py
- pydtk/db/v4/engines/mongodb.py
- pydtk/db/v4/engines/montydb.py
- pydtk/db/v4/engines/tinydb.py
- pydtk/db/v4/engines/tinymongo.py
- pydtk/db/v4/handlers/__init__.py
- pydtk/models/__init__.py
Fix dataware-tools/dataware-tools#99
Bug fix
> Avoid using root logger

- pydtk/models/movie.py
- Update video reading process
- To reduce the number of frames to read and improve efficiency
> Update video reading process

- docker/runtime/ubuntu-18.04-ros.Dockerfile
- docker/runtime/ubuntu-18.04.Dockerfile
- docker/runtime/ubuntu-ros.Dockerfile
- docker/runtime/ubuntu.Dockerfile
- pydtk/__init__.py
- pyproject.toml
- test/records/annotation_model_test/annotation_test.csv.json
- test/records/can_model_test/test.bag.json
- test/records/csv_model_test/data/test.csv.json
- test/records/forecast_model_test/forecast_test.csv.json
- test/records/image_model_test/sample.png.json
- test/records/json_model_test/json_test.json.json
- test/records/movie_model_test/sample.mp4.json
- test/records/rosbag_model_test/data/records.bag.json
- test/records/sample/data/records.bag.json
- test/records/sample/separated_data/records.bag.json
- test/records/zstd_rosbag_model_test/data/records.bag.zst.json
- test/test_db.py
- test/test_io.py
- test/test_models.py
Fix paths of sample files for tests
so that tests pass in local environment as well as inside a container
> fix tests run on local environment (without containers)

- .github/workflows/update_openapi_specification.yaml
- openapi/dataware-tools.com/v1alpha1/file.json
- openapi/dataware-tools.com/v1alpha1/record.json
- pydtk/bin/oas.py
- pydtk/db/schemas/__init__.py
- pydtk/db/schemas/dataware-tools.com/v1alpha1/file.py
- pydtk/db/schemas/dataware-tools.com/v1alpha1/record.py
- pyproject.toml
- Add script to dump schemas in the form of OpenAPI Specification.
- Add CI to execute the above script and make PR
- To automatically generate OpenAPI Specification.
> OpenAPI Specification

- .github/workflows/on_release.yaml
- fix https://github.com/dataware-tools/pydtk/actions/runs/3537183393/jobs/5936921479#step:5:23
- publish does not work
- https://github.com/dataware-tools/pydtk/actions/runs/3537183393/jobs/5936921479#step:5:23
> fix: fix on release github action

- openapi/dataware-tools.com/v1alpha1/annotation.json
- openapi/dataware-tools.com/v1alpha1/annotation_commented_image_pixel.json
- openapi/dataware-tools.com/v1alpha1/annotation_commented_image_rectangular_area.json
- openapi/dataware-tools.com/v1alpha1/annotation_commented_point.json
- pydtk/db/schemas/__init__.py
- pydtk/db/schemas/dataware-tools.com/v1alpha1/annotation.py
- pydtk/db/schemas/dataware-tools.com/v1alpha1/annotation_commented_image_pixel.py
- pydtk/db/schemas/dataware-tools.com/v1alpha1/annotation_commented_image_rectangular_area.py
- pydtk/db/schemas/dataware-tools.com/v1alpha1/annotation_commented_point.py
- test/test_db.py
- Add annotation models
- To support various types of annotations
> feat: add annotation models

- pydtk/db/v4/handlers/__init__.py
- pydtk/db/v4/handlers/meta.py
- test/test_db.py
- support migration of meta database
- to migrate database from the old version
Before
```json
{
"database_id_df": {
"1": {
"database_id": "old",
"df_name": "db_7bb29237_meta",
"_uuid": "149603e6c03516362a8da23f624db945",
"_creation_time": 1669881528.823105
}
},
"--config--database_id_df": {
"1": {
"columns": [
{
"name": "database_id",
"dtype": "string",
"aggregation": "first",
"display_name": "Database ID"
},
{
"name": "df_name",
"dtype": "string",
"aggregation": "first",
"display_name": "DataFrame name"
}
],
"index_columns": [
"database_id"
],
"_uuid": "__config__"
}
},
"db_7bb29237_meta": {
"1": {
"description": "Description",
"record_id": "sample",
"data_type": "raw_data",
"path": "test/records/sample/data/records.bag",
"start_timestamp": 1550125637.22,
"end_timestamp": 1550125637.53, …
```
> feat: support migration of meta database

- pydtk/db/__init__.py
- pydtk/db/v4/__init__.py
- pydtk/db/v4/handlers/annotation.py
- test/annotations/annotation_commented_image_pixel.json
- test/annotations/annotation_commented_image_rectangular_area.json
- test/annotations/annotation_commented_point.json
- test/test_annotations.py
- Add AnnotationDBHandler
- Handle annotation data
> feat: annotation db handler

- pydtk/conf/v4.yaml
- pydtk/db/v4/handlers/annotation.py
- Add annotation handler config
- To set default values from the config file
> fix: annotation handler config

- .github/workflows/build_and_publish_images.yml
- .github/workflows/ci.yaml
- docker/base/ubuntu-20.04-ros2.Dockerfile
- docker/dev/ubuntu-20.04-ros2.Dockerfile
- docker/dev/ubuntu-ros2.Dockerfile
- docker/runtime/ubuntu-20.04-ros2.Dockerfile
- docker/runtime/ubuntu-ros2.Dockerfile
- docker/targets.txt
- poetry.lock
- pyproject.toml
- Add ROS2 Dockerfile
- To support rosbag2
> feat: ROS2 image

- .github/workflows/ci.yaml
- Makefile
- pydtk/models/rosbag2.py
- test/test_models.py
- tox.ini
- Enable to test some msg types
- to test some msg types
> feat: update to specify topic types and add msg types for tests

- docker/base/ubuntu-20.04-ros2.Dockerfile
- pydtk/models/rosbag2.py
- test/test_models.py
- Enable us to convert rosbag2 msg into flat dict
- Want to load various msgs as array or value
> feat: support recursive conversion of rosbag2 msg into flatdict

- pydtk/models/rosbag2.py
- Check if Python version is 3.8 in rosbag2
- For package dependencies
> feat: check python version in rosbag2

- docker/base/ubuntu-20.04-ros2.Dockerfile
- pydtk/models/rosbag2.py
- test/test_models.py
- Support mcap format of rosbag2 file
- Both db3 and mcap are used in ROS2
> feat: support rosbag2 mcap format 

- openapi/dataware-tools.com/v1alpha2/annotation.json
- openapi/dataware-tools.com/v1alpha2/annotation_commented_image_pixel.json
- openapi/dataware-tools.com/v1alpha2/annotation_commented_image_rectangular_area.json
- openapi/dataware-tools.com/v1alpha2/annotation_commented_point.json
- openapi/dataware-tools.com/v1alpha2/file.json
- openapi/dataware-tools.com/v1alpha2/record.json
- pydtk/db/schemas/__init__.py
- pydtk/db/schemas/dataware-tools.com/v1alpha2/annotation.py
- pydtk/db/schemas/dataware-tools.com/v1alpha2/annotation_commented_image_pixel.py
- pydtk/db/schemas/dataware-tools.com/v1alpha2/annotation_commented_image_rectangular_area.py
- pydtk/db/schemas/dataware-tools.com/v1alpha2/annotation_commented_point.py
- pydtk/db/schemas/dataware-tools.com/v1alpha2/file.py
- pydtk/db/schemas/dataware-tools.com/v1alpha2/record.py
- test/annotations/annotation_commented_image_pixel.json
- test/annotations/annotation_commented_image_rectangular_area.json
- test/annotations/annotation_commented_point.json
- make timestamp nullable
- timestamp may be null
[Workaround for make properties nullable in pydantic v1.](https://github.com/pydantic/pydantic/issues/1270#issuecomment-734454493)
[Issue related nullable property will be resolved in v2.](https://docs.pydantic.dev/blog/pydantic-v2/#required-vs-nullable-cleanup)
> fix: make timestamp nullable

- pydtk/bin/sub_commands/db.py
- pydtk/bin/sub_commands/model.py
- pydtk/utils/utils.py
- test/test_cli.py
- Fix a bug that caused an error when specifying only numeric database_id in the CLI
- Allow only numeric database_id to be specified
> fix: fix cli bug related to database id

- docker/base/ubuntu-22.04-ros2.Dockerfile
- pydtk/models/rosbag2.py
- Update ROS2 image and model
- Wanna to generate more metadata
```
(pydtk-py3.10) root@kan-bayashi-deploy-0:/opt/pydtk# pydtk model generate metadata --from-file sample/sample_autoware.db3
[WARN] [1674713541.242857171] [rosbag2_storage]: No storage plugin found with id 'sqlite3'.
[INFO] [1674713541.265295821] [rosbag2_storage]: Opened database 'sample/sample_autoware.db3' for READ_ONLY.
[WARN] [1674713541.437573104] [rosbag2_storage]: No storage plugin found with id 'sqlite3'.
[INFO] [1674713541.442175123] [rosbag2_storage]: Opened database 'sample/sample_autoware.db3' for READ_ONLY.
[WARN] [1674713541.613120382] [rosbag2_storage]: No storage plugin found with id 'sqlite3'.
[INFO] [1674713541.617680635] [rosbag2_storage]: Opened database 'sample/sample_autoware.db3' for READ_ONLY.
{ …
```
> Update ROS2 image and model

- docker/base/ubuntu-22.04-ros2.Dockerfile
- pydtk/models/rosbag2.py
- Update ROS2 image
- To add new dependencies
> Update ROS2 image

- pydtk/models/rosbag2.py
Support seeking rosbag2 (mcap format) with the latest `rosbag2_py` package.
> feat: support seeking rosbag2 (mcap format)

- pydtk/db/schemas/dataware-tools.com/v1alpha5/annotation.py
- pydtk/db/schemas/dataware-tools.com/v1alpha5/annotation_commented_image_pixel.py
- pydtk/db/schemas/dataware-tools.com/v1alpha5/annotation_commented_image_rectangular_area.py
- pydtk/db/schemas/dataware-tools.com/v1alpha5/annotation_commented_point.py
Update image pixel unit from int to float.
These values can be float in the scene-viewer app.
> fix: image pixel unit to float

- pydtk/db/schemas/dataware-tools.com/v1alpha1/annotation_commented_image_pixel.py
- pydtk/db/schemas/dataware-tools.com/v1alpha1/annotation_commented_image_rectangular_area.py
- pydtk/db/schemas/dataware-tools.com/v1alpha1/annotation_commented_point.py
- pydtk/db/schemas/dataware-tools.com/v1alpha2/annotation_commented_image_pixel.py
- pydtk/db/schemas/dataware-tools.com/v1alpha2/annotation_commented_image_rectangular_area.py
- pydtk/db/schemas/dataware-tools.com/v1alpha2/annotation_commented_point.py
- pydtk/db/schemas/dataware-tools.com/v1alpha3/annotation_commented_image_pixel.py
- pydtk/db/schemas/dataware-tools.com/v1alpha3/annotation_commented_image_rectangular_area.py
- pydtk/db/schemas/dataware-tools.com/v1alpha3/annotation_commented_point.py
- pydtk/db/schemas/dataware-tools.com/v1alpha4/annotation_commented_image_pixel.py
- pydtk/db/schemas/dataware-tools.com/v1alpha4/annotation_commented_image_rectangular_area.py
- pydtk/db/schemas/dataware-tools.com/v1alpha4/annotation_commented_point.py
- pydtk/db/schemas/dataware-tools.com/v1alpha5/annotation_commented_image_pixel.py
- pydtk/db/schemas/dataware-tools.com/v1alpha5/annotation_commented_image_rectangular_area.py
- pydtk/db/schemas/dataware-tools.com/v1alpha5/annotation_commented_point.py
- pydtk/utils/imports.py
- test/test_db.py
Fix the bug that modules are not imported properly in db/schemas
bug fix
> fix: bug that modules were not imported properly in db/schemas

- pydtk/db/schemas/dataware-tools.com/v1alpha5/annotation.py
Add schema `ArbitraryAnnotation`
To store arbitrary annotations
> feat: add schema arbitrary-annotation
