dataware-tools/pydtk

pydtk/db/v3/handlers/meta.py
Fix the bug that df_name was used as the target database in `DatabaseIDDBHandler`
Bug fix
=> Fix the bug that `DatabaseIDDBHandler` uses a wrong database

README.md, doc/source/index.rst
Use `pip` instead of `poetry` to install this package in README.
`pip` is more popular with installing Python packages.
=> Simplify the instruction for installing this package

pydtk/models/csv.py
- Fix AnnotationCsvModel not to return nan as Risk_factor.
- API で NaN を返さないようにするため
- ↑ だけなら API でデータを整えてもいいが，NaNより空文字を返す方が，型が適当なため
=> Fix AnnotationCsvModel not to return nan as Risk_factor

pydtk/db/v2/handlers/__init__.py
- fix DBHandler not to use default username and password when only pasword is empty
- to use easily when pydtk user want to create username(or role) that have empty pasword
=> fix DBHandler to allow empty password

pydtk/io/__init__.py, pydtk/io/errors.py, pydtk/io/reader.py, pydtk/io/writer.py
- add io.errors
- in examples/02_grab_data_based_on_metadata.ipynb, NoModelMatcedError is imported from pydtk.io.
=> add io.errors

pydtk/conf/v3.yaml
Use `content_type` as an additional column to index meta_df
To handle files with different content-type but the same content-name
=> Add `content_type` to the index columns of meta_df

pydtk/db/v3/handlers/__init__.py
- `DBHandler.read()` が正しく実行された後に `DBHandler.read()` が失敗すると，`DBHandler.df` 内の `creation_time_in_df` が重複するバグの修正
- バグ修正
1. `DBHandler.df` の `setter` 内で `DBHandler.columns` もセットされるため，`DBHandler.read()` が成功すると `DBHandler.columns` に `uuid_in_df` と `creation_time_in_df` が含まれるようになる
2. この状態で `DBHandler.read()` が失敗すると，`DBHandler._initialize_df()` の結果が `df.setter` に与えられる
3. `DBHandler._initialize_df()` は `DBHandler.columns` が何であろうと それに `uuid_in_df` と `creation_time_in_df` を加えて返すため，`DBHandler.df` 内の  `creation_time_in_df` が重複する．`uuid_id_df` は ` df.set_index('uuid_in_df', inplace=True)` で消える
4. この状態で `DBHandler.add_data()` を実行すると，その内部の `pandas.concat` で `ValueError: Plan shapes are not aligned` が発生する
```
$ docker exec -it pydtk python3
>>> from pydtk.db import V3DBHandler as DBHandler
>>> handler = …
```
=> fix bug that "creation_time_in_df" in DBHandler.df duplicate after falilure of DBHandler.read() 

.github/workflows/on_release.yaml, pyproject.toml
Add GitHub workflow `on_release.yaml` to publish a pre-built package on release
To automate workflow
- Current implementation is published as v0.0.0 to reserve name `pydtk` in PyPI
- Git dependencies must be removed from `pyproject.toml` to publish
=> Add CI to publish to PyPI on release

pydtk/conf/v4.yaml, pydtk/db/v4/handlers/__init__.py, pydtk/db/v4/handlers/meta.py, test/test_db_v4.py
Support for customizing names for columns to display in V4DBHandler.
This resolves #36 
This feature is useful in case you want to rename columns to display after adding metadata.
https://www.notion.so/humandatawarelab/V4DBHandler-179102ec58db4bf596559e5b976b467b
=> Support for `display_name` in V4DBHandler

pydtk/models/csv.py, pydtk/models/json_model.py, pydtk/models/movie.py, pydtk/models/pointcloud/pcd.py, pydtk/models/rosbag.py, test/test_make_meta.py
`generate_contents_meta` 関数が一部、dictではなくlist形式を返していたバグを修正
バグ修正のため
https://github.com/dataware-tools/pydtk/issues/32#issuecomment-790514698
=> Fix the bug that `generate_contents_meta` returns list but not dict

pydtk/bin/make_meta.py, pydtk/conf/v4.yaml, pydtk/utils/utils.py
- meta-maker で `--out_dir` オプションを指定しないと標準出力にメタ情報を出力する仕様に変更
- `_select_model` が `pydtk.io.reader` 内の実装とダブっていたので置き換え
- `common_item` を `pydtk/conf/v4.yaml` に移動
- dockerコンテナ経由でメタ情報を生成する際に、出力ディレクトリをマウントしたりするのが面倒なのでこういう仕様にしてみました
=> Support dumping metadata to stdout in meta-maker

Dockerfile
Dockerfile 内での `poetry install` での `-E tinydb` オプションを削除
`pyproject.toml` に `tinydb` のエクストラが無いから
=> Remove option `-E tinydb` in dockerfile

poetry.lock, pyproject.toml
Python のバージョン指定を `>=3.7,4` に変更
pydtk に依存したパッケージをインストールする際、以下のようなエラーが発生してしまうため
```
SolverProblemError
Because pydtk (rev master) depends on pydtk (rev master) which depends on pql (<=0.4.3), pydtk (rev master) requires pql (<=0.4.3).
So, because api depends on pydtk (rev master) which depends on pql (rev 358c42b7aa15634268c41850a01a4ff9f5c0994f), version solving failed.
at /usr/local/lib/python3.8/site-packages/poetry/puzzle/solver.py:241 in _solve
237│             packages = result.packages
238│         except OverrideNeeded as e:
239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
240│         except SolveFailure as e:
→ 241│             raise SolverProblemError(e)
242│ 
243│         results = dict(
244│             depth_first_search(
245│ …
```
=> Change python dependency to '>=3.7,<4'

pydtk/db/v4/handlers/__init__.py
V4DBHandler の `save` 関数内での動作の順番を修正:
(修正前)
1. `upsert` で既存のデータの更新 & 新規データの登録
2.  削除リスト `_uuids_to_remove` に登録されているIDのデータを削除
(修正前)
1.  削除リスト `_uuids_to_remove` に登録されているIDのデータを削除
2. `upsert` で既存のデータの更新 & 新規データの登録
同一IDのデータをローカル上で削除してから追加した場合、 修正前の動作だと `save` 時に消えてしまうため
=> Fix the order of processes on saving records to DB

pydtk/utils/utils.py
関数 `dtype_string_to_dtype_object` で `DTYPE_MAP` に登録されていないデータ型が含まれる場合に `object` を返す仕様に変更
(DataFrameへの変換用に使用)
`DTYPE_MAP` にハードコーディングされていないデータ型が `config['columns']` に含まれていると例外で落ちてしまうのを防ぐため
=> Fix dtype_string_to_dtype_object

pydtk/__init__.py, pydtk/conf/v4.yaml, pydtk/db/v4/handlers/meta.py, test/test_db.py
V4MetaDBHandler のデフォルトカラムから以下を削除
- database_id
- sub_record_id
- data_type
- start_timestamp
- end_timestamp
- content_type
- mst_type
- msg_md5
- count
- frequency
汎用化するため
=> Reduce default columns of V4DBHandler

pydtk/bin/sub_commands/db.py
`pydtk db *** --parsable` コマンドの出力が JSON フォーマットになっていなかったバグを修正
バグ修正のため
=> Fix the bug that output of `pydtk db` with `--parsable` was not parsable

pydtk/bin/sub_commands/db.py, pydtk/bin/sub_commands/model.py
CLIが以下のようなエラーで失敗するバグを修正
```bash
TypeError: Object of type ObjectId is not JSON serializable
```
バグ修正のため
#54
=> Fix the bug that CLI fails with JSON unserializable errors

examples/01_grab_metadata.ipynb, examples/02_grab_data_based_on_metadata.ipynb, poetry.lock, pydtk/__init__.py, pydtk/bin/sub_commands/db.py, pydtk/db/v4/engines/tinymongo.py, pyproject.toml, test/test_db.py
- Query `"contents.{content}" == exists(True)` instead of `"contents.{content}" != ""`.
- Fix the bug that query `{key} == exists(True)` does not work properly with Tinymongo.
Bug fix
=> Fix the bug that querying the existence of contents does not work properly

pydtk/__init__.py, pydtk/conf/v4.yaml, pydtk/db/v4/handlers/meta.py, test/test_db.py
Remove `description` and `tags` from the initial columns of `MetaDBHandler`
To simplify `MetaDBHandler`
=> Simplify initial columns of `MetaDBHandler`

docker/dev/ubuntu-ros.Dockerfile, docker/dev/ubuntu.Dockerfile, docker/runtime/ubuntu-ros.Dockerfile, docker/runtime/ubuntu.Dockerfile, poetry.lock, pyproject.toml
Remove depending packages for the following components:
- V1DBHandler
- V2DBHandler
- V3DBHandler
As of v0.1.0, V4DBHandler is the standard handler.
So, V1-3 are deprecated and no longer need to be supported.
=> Remove unnecessary dependencies

pydtk/db/v4/engines/mongodb.py
Resolve https://github.com/dataware-tools/dataware-tools/issues/34
Fix the bug that listing large number of records fails with the following error.
```
pymongo.errors.OperationFailure: Exceeded memory limit for $group, but didn't allow external sort. Pass allowDiskUse:true to opt in., full error: {'ok': 0.0, 'errmsg': "Exceeded memory limit for $group, but didn't allow external sort. Pass allowDiskUse:true to opt in.", 'code': 292, 'codeName': 'QueryExceededMemoryLimitNoDiskUseAllowed'}
```
Bug fix
=> Default to `allowDiskUse=True` in MongoDB

pydtk/bin/sub_commands/db.py
Resolve https://github.com/dataware-tools/dataware-tools/issues/4
Set default to display only the first 20 items when listing resources using CLI.
=> Set default to `limit=20` when listing resources with CLI

pydtk/db/v4/handlers/__init__.py, test/test_db.py
Set the beginning index of DBHandler.df to `offset` of `read()` function
To improve usability and visibility
=> Reflect `offset` on `read()` to DBHandler.df

pydtk/bin/sub_commands/model.py, test/test_cli.py
Resolve https://github.com/dataware-tools/dataware-tools/issues/26
Add option `--model` to command `pydtk model generate`
=> Support specifying model in CLI

pydtk/bin/sub_commands/model.py, pydtk/models/__init__.py, pydtk/models/movie.py, pydtk/models/pointcloud/pcd.py, test/test_cli.py
Fix the bug that option `--content` in command `pydtk model generate metadata` had no effect
Bug fix
=> Fix the bug that option `--content` had no effect in CLI

pydtk/conf/v4.yaml, pydtk/db/v4/handlers/__init__.py, test/test_db.py
Add a function to fix data-type of the input data and call it on `add_data` in DBHandler
Fix #73 and dataware-tools/dataware-tools#50
Bug fix
=> Fix the bug that dtype of the input data was not fixed

pydtk/bin/sub_commands/db.py, pydtk/db/v4/handlers/__init__.py, test/test_cli.py
- cli db add コマンドの上書きオプション`--overwrite`を追加
- `record_id`および`path`が同一の場合、ユーザに通知せずにDBを上書きしてしまうため、上書きしてしまう際は警告を通知するようにした。
- https://github.com/dataware-tools/dataware-tools/issues/25
=> overwrite option (command: db add)

pydtk/bin/cli.py
Set default to hide tracebacks in CLI and only show them when `--verbose` option is used.
To improve user experiences
=> Hide tracebacks in CLI unless `--verbose` option is set

pydtk/db/v4/handlers/__init__.py, pydtk/db/v4/handlers/meta.py, test/test_db.py
Fix the bug that `DatabaseIDDBHandler.remove_data` drops the table which stores the metadata of the corresponding database-id before executing `save()`.
Bug fix
#81 
Test case `_test_remove_database_id` is added for this fix, but disabled as PyDTK does not support dropping tables with TinyDB < 4.  
This should be enabled when #83 is resolved.
=> Fix the bug that cascaded tables were dropped before `save()` is called

pydtk/models/json_model.py
Fix the issue that metadata of json files was not generated properly.
Bug fix
Before:
```json
{
"content": {
"keys": [
dict_keys(["key1", "key2", ...])
],
"tags": [
"json"
]
}
}
```
After:
```json
{
"content": {
"keys": [
"key1", 
"key2", 
...
],
"tags": [
"json"
]
}
}
```
=> Fix `generate_contents_meta` of GenericJsonModel

pydtk/db/v4/engines/montydb.py, test/test_db.py
Add the following options to function `read` in MontyDB
- `limit`: number of items to return per page
- `offset`: offset of cursor
- `disable_count_total`: disable counting the total number of items in the collection
=> Enrich options of function `read` in MontyDB

.dockerignore, README.md, docker-entrypoint.sh, docker/dev/ubuntu-ros.Dockerfile, docker/runtime/ubuntu-ros.Dockerfile
Pre-install the following packages in docker images tagged `ubuntu-*-ros-*`.
- ros_numpy
- pypcd
To enable ROS-related models out-of-box in containers
=> Pre-install ROS-related dependencies in docker images

pydtk/db/v4/handlers/__init__.py
Fix function `register_handler` in `pydtk.db.v4.handlers`
Bug fix
before:
```python
>>> from pydtk.db import DBHandler
Failed to load handlers in meta.py
>>> 
```
after:
```python
>>> from pydtk.db import DBHandler
>>> 
```
=> Fix the bug that function `register_handler` was not working properly

pydtk/db/v4/engines/mongodb.py, pydtk/db/v4/engines/montydb.py, pydtk/db/v4/engines/tinydb.py, pydtk/db/v4/engines/tinymongo.py, pydtk/db/v4/handlers/__init__.py, test/test_db.py
This patch includes the following bug things:
- Add function `exist_table` to check the existence of tables on DB
- Support deleting tables which are used for storing configs of V4DBHandler
- Add feature to load configs when `V4DBHandler.read()` is called
- Deprecate the feature of specifying df_name in `V4DBHandler.read()` as it may cause unexpected behavior
- Fix `test_db.py` to clean the environment on each test
To fix dataware-tools/dataware-tools#119
=> Fix the bug that configs of V4DBHandler on DB are not deleted when dropping tables

docker/base/ubuntu-18.04-ros.Dockerfile
Fix the bug that base Dockerfile of ubuntu-18.04-ros cannot be built
Bug fix
https://github.com/dataware-tools/pydtk/runs/7686786202?check_suite_focus=true
=> fix dockerfile of ubuntu-18.04-ros

pydtk/models/movie.py
- Fix checking `start_frame_idx` and `end_frame_idx`
- Although the process can read 1 frame if the same frame is specified for `start_frame_idx` and `end_frame_idx`, an error occurs when checking with assert.
When the same value is specified for `start_timestamp` and `end_timestamp`, and `floor` and `ceil` have the same value., the error will occur.
- #110
=> Enable to specify the same start and end timestamp

openapi/dataware-tools.com/v1alpha1/annotation.json, openapi/dataware-tools.com/v1alpha1/annotation_commented_image_pixel.json, openapi/dataware-tools.com/v1alpha1/annotation_commented_image_rectangular_area.json, openapi/dataware-tools.com/v1alpha1/annotation_commented_point.json, openapi/dataware-tools.com/v1alpha1/file.json, openapi/dataware-tools.com/v1alpha1/record.json, pydtk/db/schemas/__init__.py, pydtk/db/schemas/dataware-tools.com/v1alpha1/annotation.py, pydtk/db/v4/handlers/__init__.py
- fix the case where the property starting with underscore is not validated.
- property starting with underscore should be created with alias
https://pydantic-docs.helpmanual.io/usage/schema/#:~:text=and%20default_factory.-,alias,-%3A%20the%20public%20name
=> fix: fix property starting with underscore

.github/workflows/build_and_deploy_document.yaml, .github/workflows/build_and_publish_images.yml
- drop the support of ubuntu 18.04 in docker build ci
- we support only ubuntu >= 20.04
=> fix: drop the support of ubuntu 18.04 in docker-build ci

openapi/dataware-tools.com/v1alpha2/file.json, openapi/dataware-tools.com/v1alpha2/record.json, pydtk/db/schemas/dataware-tools.com/v1alpha2/file.py, pydtk/db/schemas/dataware-tools.com/v1alpha2/record.py
Add `"additionalProperties": {}` to OpenAPI spec files of Record and File models.
To align with the existing data
https://swagger.io/docs/specification/data-models/dictionaries/#:~:text=type%3A%20string-,Free%2DForm%20Objects,-If%20the%20dictionary
=> fix: allow additional properties in Record and File

pydtk/conf/v4.yaml, pydtk/db/v4/handlers/annotation.py
- fix default name entry in default config
- To use `db_class` as the default config entry name
=> fix: fix wrong name entry in default config

pydtk/db/schemas/dataware-tools.com/v1alpha5/annotation.py, pydtk/db/schemas/dataware-tools.com/v1alpha5/arbitrary_annotation.py
Move ArbitraryAnnotation class to a separated file
To generate OpenAPI specifications properly
#156
=> fix: separate file of arbitrary-annotation

pydtk/db/schemas/dataware-tools.com/v1alpha5/arbitrary_annotation.py
Fix schema ArbitraryAnnotation
To generate OpenAPI specifications properly
=> fix: add schema_extra to arbitrary-annotation

pydtk/conf/v4.yaml
Add start_timestamp and end_timestamp fields with min and max aggregation to meta db configuration.
To derive the start and end timestamp of a record.
=> feat: add start and end timestamp to meta db config

pydtk/db/schemas/__init__.py
Make _kind and _api_version to be optional in schemas.
To solve error on validating api response when _kind or _api_version is absent.
=> feat: make _kind and _api_version to be optional

pydtk/db/schemas/__init__.py
Remove _api_version and _kind from required fields.
To solve error on validating api response when _kind or _api_version is absent.
=> feat: remove _api_version and _kind from required fields

pydtk/db/schemas/dataware-tools.com/v1alpha2/annotation_commented_image_rectangular_area.py, pydtk/db/schemas/dataware-tools.com/v1alpha5/annotation_commented_image_pixel.py, pydtk/db/schemas/dataware-tools.com/v1alpha5/annotation_commented_image_rectangular_area.py
- add optional property (instance id) to AnnotationCommentedImageRectanglerArea 
- To track annotated instance 
https://www.notion.so/humandatawarelab/scene-viewer-943bb4841bb44aa7b1751ae5d41629a6?pvs=4
=> feat: add optional property to AnnotationCommentedImageRectanglerArea
